In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
## sentences -
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good devloper',
    'understand the meaning of words',
    'video games are good',
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good devloper',
 'understand the meaning of words',
 'video games are good']

In [9]:
## Define the vocabulary size
voc_size = 10000

In [10]:
### one hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3337, 2377, 2706, 3094],
 [3337, 2377, 2706, 2925],
 [3337, 3995, 2706, 3934],
 [1443, 4933, 3804, 8101, 1090],
 [1443, 4933, 3804, 8101, 8841],
 [9824, 3337, 6785, 2706, 6232],
 [9039, 2458, 8330, 8101]]

the above are index of words

In [12]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [16]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
# embedded_docs = pad_sequences(one_hot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3337 2377 2706 3094]
 [   0    0    0    0 3337 2377 2706 2925]
 [   0    0    0    0 3337 3995 2706 3934]
 [   0    0    0 1443 4933 3804 8101 1090]
 [   0    0    0 1443 4933 3804 8101 8841]
 [   0    0    0 9824 3337 6785 2706 6232]
 [   0    0    0    0 9039 2458 8330 8101]]


here by using `pad sequences` we have add leading zeros to get the sentance length of `8` that we have defined 

In [17]:
## feature representation

dim = 10 # feature dimention of 10

In [18]:
# create model
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse') # using optimizer `adam` and loss function `mse`

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 433ms/step


array([[[ 4.6740603e-02,  4.9677301e-02,  3.6447454e-02,  4.6438504e-02,
          4.4198874e-02,  4.2145360e-02, -1.3247777e-02,  2.8784040e-02,
         -3.2281056e-03, -1.5091501e-02],
        [ 4.6740603e-02,  4.9677301e-02,  3.6447454e-02,  4.6438504e-02,
          4.4198874e-02,  4.2145360e-02, -1.3247777e-02,  2.8784040e-02,
         -3.2281056e-03, -1.5091501e-02],
        [ 4.6740603e-02,  4.9677301e-02,  3.6447454e-02,  4.6438504e-02,
          4.4198874e-02,  4.2145360e-02, -1.3247777e-02,  2.8784040e-02,
         -3.2281056e-03, -1.5091501e-02],
        [ 4.6740603e-02,  4.9677301e-02,  3.6447454e-02,  4.6438504e-02,
          4.4198874e-02,  4.2145360e-02, -1.3247777e-02,  2.8784040e-02,
         -3.2281056e-03, -1.5091501e-02],
        [-1.1866104e-02, -9.4570294e-03,  3.7176523e-02,  1.7984841e-02,
         -2.8553808e-02,  1.4511537e-02, -4.0435791e-04,  4.7840085e-02,
         -3.9427519e-02, -2.3076272e-02],
        [ 9.8013766e-03,  1.6861055e-02, -4.9910963e-02,  2.

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 3337, 2377, 2706, 3094])